server:
  port: 8090
spring:
  application:
    name: backend
  main:
    banner-mode: off
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://finalproject.cahpjkshbqdh.eu-west-1.rds.amazonaws.com:3306/phonebook}
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:23528861}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8091}
  endpoints:
    web:
      exposure:
        include: info, health
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: false
    info:
      enabled: true


